### ISSUE TITLE
 JGB-006 Authentification

### ISSUE THREAD

**Issue by MihaiCampeanu** [msgjt/2017s2grB#10]
Ca si un   user al aplicatiei asi vreau sa am posibilitatea sa ma loghez cu usernamul   meu folosind o parola.

**Comment by mirceatgrosu** [comment]
La **Assignees**, in general, ar trebui sa fie cineva adaugat daca este **In Progress**.
La **Estimate** se poate pune estimarea initiala sau una mai potrivita, daca e cazul, cand se pune **In Progress**.

**Comment by MihaiCampeanu** [comment]
Userul se dezactiveaza dupa 5 incercari esuate de login.
