### ISSUE TITLE
JBG-016 Internationalization	

### ISSUE THREAD

**Issue by MihaiCampeanu** [msgjt/2017s2grB#15]
Ca si un user al aplicatiei asi   vreau sa am posibilitatea sa schimb limba in care se afiseaza continutul   aplicatiei avand posibilitatea sa aleg intre Romana si Engleza.

**Comment by mirceatgrosu** [comment]
La **Assignees**, in general, ar trebui sa fie cineva adaugat daca este **In Progress**.
La **Estimate** se poate pune estimarea initiala sau una mai potrivita, daca e cazul, cand se pune **In Progress**.
